version: 2
jobs:
  license:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run: ./script/check-licenses.sh
  vet:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run: go vet ./...
  test:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run: go test -race -cover ./...
  smoke-test:
    docker:
      - image: golang:1.19
    steps:
      - checkout
      - run: go run ./cmd/clusterlint --version
workflows:
  version: 2
  all:
    jobs:
      - license
      - vet
      - test
      - smoke-test
